name: build all images
on:
  push:
    branches: [main]
    paths:
    - '*/Dockerfile'
    - '*/version.sh'
    - '*/platforms'
    - '.github/workflows/images-build.yaml'
    - '.github/workflows/image-build.yaml'
    - '.functions/**'
  schedule:
  - cron: '0 2 */3 * *'
  workflow_dispatch:

jobs:
  list_all:
    runs-on: ubuntu-latest
    outputs:
      IMAGES: ${{ steps.list.outputs.images }}

    steps:
    - name: fetch repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: get all repo
      id: list
      run: |
        echo "images=`ls -l | grep ^d | awk '{print $NF}' | jq  --raw-input .  | jq -c --slurp . `" >> $GITHUB_OUTPUT

  build:
    permissions:
      contents: write
      packages: write
      id-token: write
    needs:
    - list_all
    uses: asterwyx/images/.github/workflows/image-build.yaml@main
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.list_all.outputs.IMAGES) }}
    with:
        DOCKER_IMAGE: ${{ matrix.image }}
